export const ADD_ITEM="ADD_ITEM"

export const GET_LIST_ITEMS_START="GET_LIST_ITEMS_START"
export const GET_LIST_ITEMS_SUCCESS="GET_LIST_ITEMS_SUCCESS"
export const GET_LIST_ITEMS_FAIL="GET_LIST_ITEMS_FAIL"

export const GET_ITEM_START="GET_ITEM_START"
export const GET_ITEM_SUCCESS="GET_ITEM_SUCCESS"
export const GET_ITEM_FAIL="GET_ITEM_FAIL"